CREATE TABLE funcionario (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   CONSTRAINT pk_funcionario PRIMARY KEY (id)
);

CREATE TABLE animal (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome_provisorio VARCHAR(255) NOT NULL,
   idade_estimada INT NOT NULL,
   especie VARCHAR(255) NOT NULL,
   raca VARCHAR(255) NOT NULL,
   data_entrada date NOT NULL,
   data_adocao date,
   condicoes_chegada VARCHAR(255) NOT NULL,
   funcionario_id INT NOT NULL,
   data_obito date,
   porte VARCHAR(255) NOT NULL,
   CONSTRAINT pk_animal PRIMARY KEY (id)
);

ALTER TABLE animal ADD CONSTRAINT FK_ANIMAL_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES funcionario (id);